require "spec_helper"
require "taskmate/config"
require "taskmate/doctor/runner"
require "taskmate/core/pull_issue"
require "taskmate/core/push_issue"
require "taskmate/core/validate_issue"
require "taskmate/workspace/diff"
require "taskmate/workspace/issue_file"
require "taskmate/security/policy"

# Verifies that Config::Loader is fully compatible with the workspace.yml
# generated by `taskmate init` (non-interactive mode), and that the
# init → doctor → pull → validate → diff → push workflow works end-to-end.
RSpec.describe "End-to-end with init-generated config", type: :integration do
  let(:workspace) { create_temp_workspace(initialized: true) }

  let(:jira_client) do
    FakeJiraClient.new(issues: {
                         "INIT-1" => {
                           "summary" => "Init config compatibility test",
                           "priority" => { "name" => "Medium", "id" => "3" },
                           "labels" => ["integration"],
                           "status" => { "name" => "To Do", "id" => "1",
                                         "statusCategory" => { "key" => "new" } }
                         }
                       })
  end

  let(:fake_policy) do
    policy = instance_double(Taskmate::Security::Policy)
    allow(policy).to receive_messages(
      authorize_jira_write: :allow,
      write_action_audit: "/tmp/audit_init_spec.yml"
    )
    policy
  end

  # ─── Config compatibility ────────────────────────────────────────────────

  describe "Config::Loader with init-generated workspace.yml" do
    subject(:cfg) { Taskmate::Config::Loader.load(workspace, env: {}) }

    it "loads without errors and returns AppConfig" do
      expect(cfg).to be_a(Taskmate::Config::AppConfig)
    end

    it "has ai.provider disabled (init default)" do
      expect(cfg.ai.provider).to eq("disabled")
    end

    it "has all three security flags set to true" do
      expect(cfg.security.require_consent_for_ai).to be(true)
      expect(cfg.security.require_confirm_for_push).to be(true)
      expect(cfg.security.secret_detection).to be(true)
    end

    it "has standard push.allowed_fields" do
      expect(cfg.push.allowed_fields).to eq(%w[summary description labels components priority])
    end

    it "has empty tracker.base_url (no URL entered during non-interactive init)" do
      expect(cfg.tracker.base_url).to eq("")
    end
  end

  # ─── Config::Validator compatibility ─────────────────────────────────────

  describe "Config::Validator with init-generated workspace.yml" do
    it "finds no validation errors" do
      raw = Taskmate::Config::Loader.load_raw(workspace)
      expect(Taskmate::Config::Validator.errors(raw)).to eq([])
    end
  end

  # ─── Doctor ──────────────────────────────────────────────────────────────

  describe "Doctor runner with init-generated workspace" do
    it "passes workspace.yml and security config checks (no :fail)" do
      checks = Taskmate::Doctor::Runner.new(workspace_path: workspace).run
      failed = checks.select { |c| c.status == :fail }
      expect(failed).to be_empty,
                        "Expected no failures but got: #{failed.map { |c| "#{c.name}: #{c.message}" }.join(', ')}"
    end

    it "workspace.yml check is :ok" do
      checks = Taskmate::Doctor::Runner.new(workspace_path: workspace).run
      check = checks.find { |c| c.name == "workspace.yml" }
      expect(check.status).to eq(:ok)
    end

    it "security config check is :ok" do
      checks = Taskmate::Doctor::Runner.new(workspace_path: workspace).run
      check = checks.find { |c| c.name == "security config" }
      expect(check.status).to eq(:ok)
    end
  end

  # ─── Full workflow ────────────────────────────────────────────────────────

  describe "pull → validate → diff → push using init-generated config" do
    it "completes all steps successfully" do
      # Step 1: Pull issue
      pull_result = Taskmate::Core::PullIssue.new(
        workspace_path: workspace,
        jira_client: jira_client
      ).call("INIT-1")
      expect(pull_result.issue_file.key).to eq("INIT-1")
      expect(File.exist?(pull_result.path)).to be(true)

      # Step 2: Validate — should pass since ADF → Markdown produces valid output
      validate_result = Taskmate::Core::ValidateIssue.new(workspace_path: workspace).call("INIT-1")
      expect(validate_result.valid?).to be(true)

      # Step 3: Diff — synced copy was written by pull, should be clean
      issue_file = Taskmate::Workspace::IssueFile.read(pull_result.path)
      diff = Taskmate::Workspace::Diff.compute(issue_file)
      expect(diff.empty?).to be(true)

      # Step 4: Push — build push_config from Config::Loader (proves compatibility)
      cfg = Taskmate::Config::Loader.load(workspace, env: {})
      push_config = cfg.push.allowed_fields.to_h { |f| ["allow_#{f}", true] }

      push_result = Taskmate::Core::PushIssue.new(
        workspace_path: workspace,
        jira_client: jira_client,
        security_policy: fake_policy,
        push_config: push_config
      ).call("INIT-1")
      expect(push_result.applied).to be(true)
    end
  end
end
